image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      git clone https://github.com/dragnet-org/dragnet.git /workspace/dragnet/ && 
      cd /workspace/dragnet &&
      pip install -r requirements.txt &&
      make install &&
      pip install scrapy pymongo
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - command: scrapy crawl SustainabilityBot




