tasks:
  - init: echo "Replace me with a build script for the project."
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - command: scrapy crawl SustainabilityBot

image:
  file: .gitpod.Dockerfile
